export interface Company {
  name: string;
  greenhouse?: string;
  lever?: string;
  workday?: string;
  custom?: string;
}

export const COMPANIES: Company[] = [
  { name: "SpaceX", custom: "spacex" },
  { name: "Tesla", custom: "tesla" },
  { name: "Rivian", custom: "rivian" },
  { name: "Pratt & Whitney" },
  { name: "Rolls Royce" },
  { name: "Northrop Grumman", greenhouse: "northropgrumman" },
  { name: "RTX", workday: "rtx" },
  { name: "Raytheon" },
  { name: "BAE Systems" },
  { name: "Moog" },
  { name: "Emerson" },
  { name: "Eaton" },
  { name: "Schneider Electric" },
  { name: "Siemens" },
  { name: "Bosch" },
  { name: "Toyota" },
  { name: "Honda" },
  { name: "Hyundai" },
  { name: "BMW" },
  { name: "Mercedes-Benz" },
  { name: "Volvo" },
  { name: "John Deere", greenhouse: "deere" },
  { name: "CNH Industrial" },
  { name: "Komatsu" },
  { name: "Polaris" },
  { name: "Whirlpool" },
  { name: "Dyson" },
  { name: "3M" },
  { name: "Johnson Controls" },
  { name: "Anduril", greenhouse: "andurilindustries" },
  { name: "Apple" },
  { name: "NVIDIA", lever: "nvidia" },
  { name: "Intel", lever: "intel" },
  { name: "AMD", lever: "amd" },
  { name: "Qualcomm", lever: "qualcomm" },
  { name: "Boeing", greenhouse: "boeing", lever: "boeing", workday: "boeing" },
  { name: "Lockheed Martin", greenhouse: "lockheedmartin" },
  { name: "Blue Origin", greenhouse: "blueorigin" },
  { name: "GE Aerospace", greenhouse: "geaerospace" },
  { name: "Honeywell", greenhouse: "honeywell" },
  { name: "Cummins", greenhouse: "cummins" },
  { name: "Caterpillar", greenhouse: "caterpillar" },
  { name: "Ford", greenhouse: "ford", lever: "ford" },
  { name: "General Motors", greenhouse: "gm", lever: "general-motors" },
  { name: "Lucid", greenhouse: "lucid", lever: "lucid" },
  { name: "Medtronic", greenhouse: "medtronic" },
  { name: "Boston Scientific", greenhouse: "bostonscientific" },
  { name: "Applied Materials", greenhouse: "appliedmaterials" },
  { name: "Lam Research", greenhouse: "lamresearch" },
  { name: "ASML" },
  { name: "Honeywell Aerospace", greenhouse: "honeywell" },
  { name: "Hermeus" },
  { name: "Boom Supersonic" },
  { name: "Virgin Galactic" },
  { name: "Textron" },
  { name: "Spirit AeroSystems" },
  { name: "Safran" },
  { name: "Relativity Space" },
  { name: "Rocket Lab" },
  { name: "Joby Aviation" },
  { name: "Archer Aviation" },
  { name: "Boston Dynamics" },
  { name: "Agility Robotics" },
  { name: "Figure AI" },
  { name: "Intrinsic" },
  { name: "Rockwell Automation" },
  { name: "Trane Technologies" },
  { name: "Carrier" },
  { name: "Atlas Copco" },
  { name: "KLA" },
  { name: "Tokyo Electron" },
  { name: "GlobalFoundries" },
  { name: "TSMC" },
  { name: "Micron" },
  { name: "Stryker" },
  { name: "Abbott" },
  { name: "J&J" },
  { name: "Zimmer Biomet" }
];
