export interface WorkdayBoard { host: string; tenant: string; site: string }
export interface Company {
  name: string;
  greenhouse?: string;
  lever?: string;
  workday?: string | WorkdayBoard;
  ashby?: string;
  icims?: string;
  phenom?: string;
  custom?: string;
  priority?: number;
}

export const COMPANIES: Company[] = [
  { name: "SpaceX", custom: "spacex", priority: 5 },
  { name: "Tesla", custom: "tesla", priority: 5 },
  { name: "Rivian", custom: "rivian", priority: 5 },
  { name: "Pratt & Whitney", workday: "pratt-whitney", priority: 5 },
  { name: "Rolls Royce", workday: "rollsroyce", priority: 5 },
  { name: "Northrop Grumman", priority: 5 },
  { name: "RTX", workday: "rtx", priority: 5 },
  { name: "Raytheon", workday: "rtx", priority: 5 },
  { name: "BAE Systems", workday: "baesystems", priority: 5 },
  { name: "Moog", workday: "moog", priority: 5 },
  { name: "Emerson" },
  { name: "Eaton", workday: "eaton", priority: 4 },
  { name: "Schneider Electric", workday: "schneider-electric", priority: 4 },
  { name: "Siemens" },
  { name: "Bosch" },
  { name: "Toyota", workday: "toyota" },
  { name: "Honda" },
  { name: "Hyundai" },
  { name: "BMW" },
  { name: "Mercedes-Benz" },
  { name: "Volvo" },
  { name: "John Deere", greenhouse: "deere", priority: 5 },
  { name: "CNH Industrial" },
  { name: "Komatsu" },
  { name: "Polaris" },
  { name: "Whirlpool" },
  { name: "Dyson" },
  { name: "3M", workday: "3m", priority: 4 },
  { name: "Johnson Controls" },
  { name: "Anduril", greenhouse: "andurilindustries", priority: 5 },
  { name: "Apple", priority: 5 },
  { name: "NVIDIA", lever: "nvidia", priority: 5 },
  { name: "Intel", lever: "intel" },
  { name: "AMD", lever: "amd" },
  { name: "Qualcomm", lever: "qualcomm" },
  { name: "Boeing", greenhouse: "boeing", lever: "boeing", workday: "boeing", priority: 5 },
  { name: "Lockheed Martin", greenhouse: "lockheedmartin", priority: 5 },
  { name: "Blue Origin", workday: { host: "blueorigin.wd5.myworkdayjobs.com", tenant: "blueorigin", site: "BlueOrigin" }, priority: 5 },
  { name: "GE Aerospace", greenhouse: "geaerospace", priority: 5 },
  { name: "Honeywell", greenhouse: "honeywell", priority: 5 },
  { name: "Cummins", greenhouse: "cummins", priority: 5 },
  { name: "Caterpillar", greenhouse: "caterpillar", priority: 5 },
  { name: "Ford", greenhouse: "ford", lever: "ford" },
  { name: "General Motors", greenhouse: "gm", lever: "general-motors" },
  { name: "Lucid", greenhouse: "lucid", lever: "lucid" },
  { name: "Medtronic", greenhouse: "medtronic" },
  { name: "Boston Scientific", greenhouse: "bostonscientific" },
  { name: "Applied Materials", greenhouse: "appliedmaterials", priority: 5 },
  { name: "Lam Research", greenhouse: "lamresearch", priority: 5 },
  { name: "ASML", priority: 5 },
  { name: "Honeywell Aerospace", greenhouse: "honeywell" },
  { name: "Hermeus", lever: "hermeus" },
  { name: "Boom Supersonic", custom: "rippling" },
  { name: "Virgin Galactic", phenom: "VGNVGEUS", priority: 5 },
  { name: "Textron" },
  { name: "Spirit AeroSystems", icims: "fllapscareers1-spirit", priority: 5 },
  { name: "Safran" },
  { name: "Relativity Space" },
  { name: "Rocket Lab", greenhouse: "rocketlab" },
  { name: "Joby Aviation" },
  { name: "Archer Aviation", greenhouse: "archer56" },
  { name: "Boston Dynamics", greenhouse: "bostondynamics", priority: 5 },
  { name: "Agility Robotics" },
  { name: "Figure AI" },
  { name: "Intrinsic" },
  { name: "Rockwell Automation" },
  { name: "Trane Technologies" },
  { name: "Carrier" },
  { name: "Atlas Copco" },
  { name: "KLA" },
  { name: "Tokyo Electron" },
  { name: "GlobalFoundries" },
  { name: "TSMC" },
  { name: "Micron" },
  { name: "Stryker", workday: { host: "stryker.wd1.myworkdayjobs.com", tenant: "stryker", site: "StrykerCareers" } },
  { name: "Abbott" },
  { name: "J&J" },
  { name: "Zimmer Biomet" }
  ,
  { name: "Collins Aerospace", phenom: "RAYTGLOBAL", priority: 5 },
  { name: "Bell Flight" },
  { name: "AeroVironment" },
  { name: "L3Harris", priority: 5 },
  { name: "Skydio" },
  { name: "Zipline" },
  { name: "Edwards Lifesciences" },
  { name: "Intuitive Surgical" },
  { name: "Parker Hannifin", workday: "parkerhannifin", priority: 4 },
  { name: "Danaher" },
  { name: "Garmin" },
  { name: "Meta" },
  { name: "Google" },
  { name: "Air Products", workday: { host: "airproducts.wd5.myworkdayjobs.com", tenant: "airproducts", site: "AP0001" } },
  { name: "IMEG", workday: { host: "imeg.wd1.myworkdayjobs.com", tenant: "imeg", site: "Imeg_Careers" } },
  { name: "General Matter", greenhouse: "generalmatter" },
  { name: "Etched", ashby: "Etched" },
  { name: "Overview Energy", ashby: "overviewenergy" }
];
