export interface Company {
  name: string;
  greenhouse?: string;
  lever?: string;
  workday?: string;
  icims?: string;
  custom?: string;
  priority?: number;
}

export const COMPANIES: Company[] = [
  { name: "SpaceX", custom: "spacex", priority: 5 },
  { name: "Tesla", custom: "tesla", priority: 5 },
  { name: "Rivian", custom: "rivian", priority: 5 },
  { name: "Pratt & Whitney" },
  { name: "Rolls Royce" },
  { name: "Northrop Grumman", greenhouse: "northropgrumman", priority: 5 },
  { name: "RTX", workday: "rtx", priority: 5 },
  { name: "Raytheon" },
  { name: "BAE Systems" },
  { name: "Moog" },
  { name: "Emerson" },
  { name: "Eaton" },
  { name: "Schneider Electric" },
  { name: "Siemens" },
  { name: "Bosch" },
  { name: "Toyota" },
  { name: "Honda" },
  { name: "Hyundai" },
  { name: "BMW" },
  { name: "Mercedes-Benz" },
  { name: "Volvo" },
  { name: "John Deere", greenhouse: "deere", priority: 5 },
  { name: "CNH Industrial" },
  { name: "Komatsu" },
  { name: "Polaris" },
  { name: "Whirlpool" },
  { name: "Dyson" },
  { name: "3M" },
  { name: "Johnson Controls" },
  { name: "Anduril", greenhouse: "andurilindustries", priority: 5 },
  { name: "Apple", workday: "apple", priority: 5 },
  { name: "NVIDIA", lever: "nvidia", priority: 5 },
  { name: "Intel", lever: "intel" },
  { name: "AMD", lever: "amd" },
  { name: "Qualcomm", lever: "qualcomm" },
  { name: "Boeing", greenhouse: "boeing", lever: "boeing", workday: "boeing", priority: 5 },
  { name: "Lockheed Martin", greenhouse: "lockheedmartin", priority: 5 },
  { name: "Blue Origin", greenhouse: "blueorigin", lever: "blueorigin", priority: 5 },
  { name: "GE Aerospace", greenhouse: "geaerospace", priority: 5 },
  { name: "Honeywell", greenhouse: "honeywell", priority: 5 },
  { name: "Cummins", greenhouse: "cummins", priority: 5 },
  { name: "Caterpillar", greenhouse: "caterpillar", priority: 5 },
  { name: "Ford", greenhouse: "ford", lever: "ford" },
  { name: "General Motors", greenhouse: "gm", lever: "general-motors" },
  { name: "Lucid", greenhouse: "lucid", lever: "lucid" },
  { name: "Medtronic", greenhouse: "medtronic" },
  { name: "Boston Scientific", greenhouse: "bostonscientific" },
  { name: "Applied Materials", greenhouse: "appliedmaterials", priority: 5 },
  { name: "Lam Research", greenhouse: "lamresearch", priority: 5 },
  { name: "ASML", workday: "asml", priority: 5 },
  { name: "Honeywell Aerospace", greenhouse: "honeywell" },
  { name: "Hermeus", lever: "hermeus" },
  { name: "Boom Supersonic" },
  { name: "Virgin Galactic" },
  { name: "Textron" },
  { name: "Spirit AeroSystems" },
  { name: "Safran" },
  { name: "Relativity Space" },
  { name: "Rocket Lab" },
  { name: "Joby Aviation" },
  { name: "Archer Aviation" },
  { name: "Boston Dynamics", greenhouse: "bostondynamics", priority: 5 },
  { name: "Agility Robotics" },
  { name: "Figure AI" },
  { name: "Intrinsic" },
  { name: "Rockwell Automation" },
  { name: "Trane Technologies" },
  { name: "Carrier" },
  { name: "Atlas Copco" },
  { name: "KLA" },
  { name: "Tokyo Electron" },
  { name: "GlobalFoundries" },
  { name: "TSMC" },
  { name: "Micron" },
  { name: "Stryker" },
  { name: "Abbott" },
  { name: "J&J" },
  { name: "Zimmer Biomet" }
  ,
  { name: "Collins Aerospace" },
  { name: "Bell Flight" },
  { name: "AeroVironment" },
  { name: "L3Harris" },
  { name: "Skydio" },
  { name: "Zipline" },
  { name: "Edwards Lifesciences" },
  { name: "Intuitive Surgical" },
  { name: "Parker Hannifin" },
  { name: "Danaher" },
  { name: "Garmin" },
  { name: "Meta" },
  { name: "Google" }
];
