import type { Snapshot } from "./history";
import { escapeHtml } from "./render";

export function renderBrowser(snapshot: Snapshot): string {
  const data = JSON.stringify(snapshot).replace(/</g, "\\u003c").replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029");
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>2027 Mechanical Engineering Internships</title><meta name="description" content="Browse mechanical engineering internships by company, discipline, location, and term. See when each listing was last verified.">
<style>
:root{font-family:system-ui,sans-serif;color:#172a3d;background:#eef3f8;font-size:16px;line-height:1.5}*{box-sizing:border-box}body{margin:0}header{background:#112c45;color:white;padding:2rem max(1.25rem,calc((100% - 1200px)/2))}header p{color:#cfdeeb;max-width:65ch}h1{font-size:clamp(1.7rem,4vw,2.6rem);line-height:1.15;margin:.5rem 0 1rem}.eyebrow{font-weight:700;letter-spacing:.12em;font-size:.875rem;color:#8fdbff}main{max-width:1240px;margin:auto;padding:1.25rem}a{color:#075b92}button,input,select{font:inherit;min-height:44px;border:1px solid #879bab;border-radius:5px;padding:.55rem .7rem;background:white;color:#172a3d}button{cursor:pointer}button:hover{background:#e2f1ff}input:focus,select:focus,button:focus,a:focus{outline:3px solid #0274b9;outline-offset:3px}.filters{background:white;padding:1.25rem;display:grid;grid-template-columns:2fr repeat(4,1fr);gap:1rem;border-top:4px solid #0274b9;border-radius:6px}label{display:flex;flex-direction:column;gap:.35rem;font-size:.875rem;font-weight:650;min-width:0}input,select{width:100%}.toolbar{display:flex;align-items:center;justify-content:space-between;gap:1rem;flex-wrap:wrap;margin:1.25rem 0}.results{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}article{background:white;border:1px solid #d3dfe8;border-radius:6px;padding:1.25rem;display:flex;flex-direction:column;gap:.6rem;overflow-wrap:anywhere}h2{font-size:1.15rem;margin:0}article p{margin:0}.company{font-weight:750;color:#075b92}.meta{color:#455c70;font-size:.875rem}.badge{align-self:flex-start;border-radius:4px;background:#e5f3ff;padding:.15rem .5rem;font-size:.875rem}.warning{background:#fff0cf;color:#664600}.closed{background:#eceef1;color:#424d58}.dates{display:flex;gap:1rem;flex-wrap:wrap;font-size:.875rem;margin-top:auto;padding-top:.5rem}.apply{font-weight:700;margin-top:.5rem}.empty{padding:2rem;background:white;border:1px dashed #879bab;grid-column:1/-1}details{margin:1.5rem 0;background:white;padding:1rem;border-radius:6px}summary{cursor:pointer;font-weight:650}.health{overflow:auto}table{border-collapse:collapse;width:100%;font-size:.875rem}th,td{text-align:left;padding:.7rem;border-bottom:1px solid #d3dfe8}footer{color:#455c70;font-size:.875rem;margin:2rem 0}.check{flex-direction:row;align-items:center}.check input{width:auto;min-height:auto}@media(max-width:900px){.filters{grid-template-columns:repeat(2,minmax(0,1fr))}.search{grid-column:1/-1}}@media(max-width:620px){.results,.filters{grid-template-columns:1fr}.search{grid-column:auto}header{padding:1.5rem}main{padding:1rem}}
</style></head><body><header><div class="eyebrow">MECHANICAL ENGINEERING / EARLY CAREERS</div><h1>Find your next internship.</h1><p>2027 openings, with the details to decide where to apply. Unspecified years are labeled separately; confirm the term with the employer.</p><p>Last checked: ${escapeHtml(snapshot.updatedAt ?? "Not yet checked")}</p></header>
<main><form class="filters" id="filters"><label class="search">Search roles or locations<input id="search" type="search" placeholder="Mechanical design, Boston, robotics…"></label><label>Company<select id="company"><option value="">All companies</option></select></label><label>Discipline<select id="category"><option value="">All disciplines</option></select></label><label>Location<select id="location"><option value="">All locations</option></select></label><label>Internship term<select id="term"><option value="current">2027 + unspecified</option><option value="2027">2027 in title</option><option value="unspecified">Year unspecified</option><option value="other">Other years</option><option value="all">All years</option></select></label></form>
<div class="toolbar"><p id="count" role="status" aria-live="polite"></p><label class="check"><input id="archive" type="checkbox">Include closed listings</label><button type="button" id="reset">Clear filters</button></div><div id="results" class="results"></div>
<noscript>Enable JavaScript to search listings, or read the repository README for the tables.</noscript>
<details><summary>Source health and coverage</summary><p>Failed or incomplete sources retain previous listings with a verification warning. Target companies without a scraper are listed as unconfigured.</p><div class="health"><table><thead><tr><th>Company</th><th>Source</th><th>Result</th><th>Matches</th></tr></thead><tbody id="health"></tbody></table></div></details>
<footer>Independent community tracker. Coverage is incomplete; no employer affiliation or guarantee of availability. “Last verified” means last seen in the source feed. New means first found within seven days. Jobs missing from a complete feed on two different UTC days move to the archive. Titles establish the year; posting dates do not.</footer></main>
<script type="application/json" id="data">${data}</script><script>
const snapshot=JSON.parse(document.getElementById('data').textContent),jobs=snapshot.jobs;
const el=id=>document.getElementById(id), label=s=>s.replaceAll('_',' ').replace(/\\b\\w/g,c=>c.toUpperCase());
const date=s=>s&&!Number.isNaN(Date.parse(s))?new Date(s).toISOString().slice(0,10):'Unknown';
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
for(const key of ['company','category','location']){const field=key==='company'?'companyName':key;for(const value of [...new Set(jobs.map(j=>j[field]).filter(Boolean))].sort()){const option=node('option',key==='category'?label(value):value);option.value=value;el(key).append(option);}}
for(const s of snapshot.sources){const row=node('tr');for(const value of [s.company,s.source,s.status,String(s.count)])row.append(node('td',value));el('health').append(row);}
function render(){const query=el('search').value.trim().toLowerCase(),term=el('term').value;
const found=jobs.filter(j=>(el('archive').checked||j.status!=='closed')&&(term==='all'||(term==='current'?j.term!=='other':j.term===term))&&(!el('company').value||j.companyName===el('company').value)&&(!el('category').value||j.category===el('category').value)&&(!el('location').value||j.location===el('location').value)&&[j.title,j.companyName,j.location,label(j.category)].join(' ').toLowerCase().includes(query)).sort((a,b)=>b.score-a.score||(b.lastSeenAt||'').localeCompare(a.lastSeenAt||'')||a.title.localeCompare(b.title));
el('count').textContent=found.length+' matching listing'+(found.length===1?'':'s');el('results').replaceChildren();
if(!found.length){el('results').append(node('p','No listings match these filters. Try another term, include closed listings, or clear the filters.','empty'));return;}
for(const j of found){const card=node('article');card.append(node('p',j.companyName,'company'),node('h2',j.title),node('p',j.location||'Location not specified'),node('p',label(j.category)+' · '+(j.term==='2027'?'2027 in title':j.term==='other'?'Other year':'Year unspecified'),'meta'));
const age=Date.now()-Date.parse(j.firstSeenAt),isNew=j.status==='open'&&age>=0&&age<7*86400000;card.append(node('span',j.status==='closed'?'Closed':j.status==='unverified'?'Needs verification':isNew?'New · Open':'Open','badge '+(j.status==='unverified'?'warning':j.status==='closed'?'closed':'')));
const dates=node('div',undefined,'dates');for(const [name,value] of [['Posted',j.postedAt],['First found',j.firstSeenAt],['Last verified',j.lastSeenAt]])dates.append(node('span',name+': '+date(value)));card.append(dates);
if(j.status!=='closed'){try{const url=new URL(j.url);if(['https:','http:'].includes(url.protocol)){const a=node('a',/\\/(?:careers|jobs|careers-home\\/jobs)\\/?$/.test(url.pathname)?'Visit career page →':'View job →','apply');a.href=url.href;a.target='_blank';a.rel='noopener noreferrer';card.append(a);}}catch{}}
el('results').append(card);}}
el('filters').addEventListener('submit',e=>e.preventDefault());el('filters').addEventListener('input',render);el('archive').addEventListener('change',render);el('reset').addEventListener('click',()=>{el('filters').reset();el('archive').checked=false;render();});render();
</script></body></html>`;
}
